name: Support Question
description: 使い方や挙動について問い合わせる
title: "[Support] "
labels:
  - question
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: 対象のプロダクトを選択してください。
      options:
        - BabyNote
        - SnapTrim
        - ThumbnailThumb
        - Multi-Video Player for Dropbox
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: アプリバージョン
      description: 分かる場合は記入してください。
      placeholder: 1.2.3
    validations:
      required: false

  - type: input
    id: os_device
    attributes:
      label: OSバージョン / 端末名
      placeholder: iOS 18.2 / iPhone 15 Pro
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: お問い合わせ内容
      description: 困っていることや確認したいことを記入してください。
      placeholder: できるだけ具体的に記入してください。
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: 試したこと
      description: すでに試した手順があれば記入してください。
      placeholder: "例: 再起動、再インストール など"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 補足情報
      description: 必要に応じてスクリーンショットや動画を添付してください。
      placeholder: 追加情報があれば記入してください。
    validations:
      required: false
